package com.nf2.sss.dao;

import com.nf2.sss.eneity.Deliveryorder;
import java.util.List;

public interface DeliveryorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String dStartingcity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryorder
     *
     * @mbg.generated
     */
    int insert(Deliveryorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryorder
     *
     * @mbg.generated
     */
    Deliveryorder selectByPrimaryKey(String dStartingcity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryorder
     *
     * @mbg.generated
     */
    List<Deliveryorder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Deliveryorder record);
}