package com.nf2.sss.dao;

import com.nf2.sss.eneity.Distrrange;
import java.util.List;

public interface DistrrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distrrange
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer diId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distrrange
     *
     * @mbg.generated
     */
    int insert(Distrrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distrrange
     *
     * @mbg.generated
     */
    Distrrange selectByPrimaryKey(Integer diId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distrrange
     *
     * @mbg.generated
     */
    List<Distrrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distrrange
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Distrrange record);
}