package com.nf2.sss.dao;

import com.nf2.sss.eneity.Distribution;
import java.util.List;

public interface DistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int insert(Distribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    Distribution selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    List<Distribution> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Distribution record);
}