package com.nf2.sss.dao;

import com.nf2.sss.eneity.Route;
import java.util.List;

public interface RouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int insert(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    Route selectByPrimaryKey(String rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    List<Route> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Route record);
}