package com.nf2.sss.dao;

import com.nf2.sss.eneity.Usertb;
import java.util.List;

public interface UsertbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertb
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertb
     *
     * @mbg.generated
     */
    int insert(Usertb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertb
     *
     * @mbg.generated
     */
    Usertb selectByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertb
     *
     * @mbg.generated
     */
    List<Usertb> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertb
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Usertb record);
}