package com.nf2.sss.dao;

import com.nf2.sss.eneity.Vehicle;
import java.util.List;

public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    Vehicle selectByPrimaryKey(String vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    List<Vehicle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vehicle record);
}