package com.nf2.sss.eneity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbg.generated
     */
    private String aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_name
     *
     * @mbg.generated
     */
    private String aName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_sex
     *
     * @mbg.generated
     */
    private Integer aSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.u_id
     *
     * @mbg.generated
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_state
     *
     * @mbg.generated
     */
    private Integer aState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_aTcity
     *
     * @mbg.generated
     */
    private String aAtcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_addres
     *
     * @mbg.generated
     */
    private String aAddres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_pass
     *
     * @mbg.generated
     */
    private String aPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_phoneNumb
     *
     * @mbg.generated
     */
    private String aPhonenumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_remarks
     *
     * @mbg.generated
     */
    private String aRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbg.generated
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbg.generated
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_name
     *
     * @return the value of admin.a_name
     *
     * @mbg.generated
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_name
     *
     * @param aName the value for admin.a_name
     *
     * @mbg.generated
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_sex
     *
     * @return the value of admin.a_sex
     *
     * @mbg.generated
     */
    public Integer getaSex() {
        return aSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_sex
     *
     * @param aSex the value for admin.a_sex
     *
     * @mbg.generated
     */
    public void setaSex(Integer aSex) {
        this.aSex = aSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.u_id
     *
     * @return the value of admin.u_id
     *
     * @mbg.generated
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.u_id
     *
     * @param uId the value for admin.u_id
     *
     * @mbg.generated
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_state
     *
     * @return the value of admin.a_state
     *
     * @mbg.generated
     */
    public Integer getaState() {
        return aState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_state
     *
     * @param aState the value for admin.a_state
     *
     * @mbg.generated
     */
    public void setaState(Integer aState) {
        this.aState = aState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_aTcity
     *
     * @return the value of admin.a_aTcity
     *
     * @mbg.generated
     */
    public String getaAtcity() {
        return aAtcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_aTcity
     *
     * @param aAtcity the value for admin.a_aTcity
     *
     * @mbg.generated
     */
    public void setaAtcity(String aAtcity) {
        this.aAtcity = aAtcity == null ? null : aAtcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_addres
     *
     * @return the value of admin.a_addres
     *
     * @mbg.generated
     */
    public String getaAddres() {
        return aAddres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_addres
     *
     * @param aAddres the value for admin.a_addres
     *
     * @mbg.generated
     */
    public void setaAddres(String aAddres) {
        this.aAddres = aAddres == null ? null : aAddres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_pass
     *
     * @return the value of admin.a_pass
     *
     * @mbg.generated
     */
    public String getaPass() {
        return aPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_pass
     *
     * @param aPass the value for admin.a_pass
     *
     * @mbg.generated
     */
    public void setaPass(String aPass) {
        this.aPass = aPass == null ? null : aPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_phoneNumb
     *
     * @return the value of admin.a_phoneNumb
     *
     * @mbg.generated
     */
    public String getaPhonenumb() {
        return aPhonenumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_phoneNumb
     *
     * @param aPhonenumb the value for admin.a_phoneNumb
     *
     * @mbg.generated
     */
    public void setaPhonenumb(String aPhonenumb) {
        this.aPhonenumb = aPhonenumb == null ? null : aPhonenumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_remarks
     *
     * @return the value of admin.a_remarks
     *
     * @mbg.generated
     */
    public String getaRemarks() {
        return aRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_remarks
     *
     * @param aRemarks the value for admin.a_remarks
     *
     * @mbg.generated
     */
    public void setaRemarks(String aRemarks) {
        this.aRemarks = aRemarks == null ? null : aRemarks.trim();
    }
}