package com.nf2.sss.eneity;

public class Cityarea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.ca_id
     *
     * @mbg.generated
     */
    private String caId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.ca_name
     *
     * @mbg.generated
     */
    private String caName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.c_id
     *
     * @mbg.generated
     */
    private String cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.ca_id
     *
     * @return the value of cityarea.ca_id
     *
     * @mbg.generated
     */
    public String getCaId() {
        return caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.ca_id
     *
     * @param caId the value for cityarea.ca_id
     *
     * @mbg.generated
     */
    public void setCaId(String caId) {
        this.caId = caId == null ? null : caId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.ca_name
     *
     * @return the value of cityarea.ca_name
     *
     * @mbg.generated
     */
    public String getCaName() {
        return caName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.ca_name
     *
     * @param caName the value for cityarea.ca_name
     *
     * @mbg.generated
     */
    public void setCaName(String caName) {
        this.caName = caName == null ? null : caName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.c_id
     *
     * @return the value of cityarea.c_id
     *
     * @mbg.generated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.c_id
     *
     * @param cId the value for cityarea.c_id
     *
     * @mbg.generated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }
}