package com.nf2.sss.eneity;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cu_id
     *
     * @mbg.generated
     */
    private String cuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cu_name
     *
     * @mbg.generated
     */
    private String cuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cu_sex
     *
     * @mbg.generated
     */
    private Integer cuSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.u_id
     *
     * @mbg.generated
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cu_password
     *
     * @mbg.generated
     */
    private String cuPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cu_phone
     *
     * @mbg.generated
     */
    private String cuPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cu_birth
     *
     * @mbg.generated
     */
    private Date cuBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cu_address
     *
     * @mbg.generated
     */
    private String cuAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cu_remarks
     *
     * @mbg.generated
     */
    private String cuRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cu_id
     *
     * @return the value of customer.cu_id
     *
     * @mbg.generated
     */
    public String getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cu_id
     *
     * @param cuId the value for customer.cu_id
     *
     * @mbg.generated
     */
    public void setCuId(String cuId) {
        this.cuId = cuId == null ? null : cuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cu_name
     *
     * @return the value of customer.cu_name
     *
     * @mbg.generated
     */
    public String getCuName() {
        return cuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cu_name
     *
     * @param cuName the value for customer.cu_name
     *
     * @mbg.generated
     */
    public void setCuName(String cuName) {
        this.cuName = cuName == null ? null : cuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cu_sex
     *
     * @return the value of customer.cu_sex
     *
     * @mbg.generated
     */
    public Integer getCuSex() {
        return cuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cu_sex
     *
     * @param cuSex the value for customer.cu_sex
     *
     * @mbg.generated
     */
    public void setCuSex(Integer cuSex) {
        this.cuSex = cuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.u_id
     *
     * @return the value of customer.u_id
     *
     * @mbg.generated
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.u_id
     *
     * @param uId the value for customer.u_id
     *
     * @mbg.generated
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cu_password
     *
     * @return the value of customer.cu_password
     *
     * @mbg.generated
     */
    public String getCuPassword() {
        return cuPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cu_password
     *
     * @param cuPassword the value for customer.cu_password
     *
     * @mbg.generated
     */
    public void setCuPassword(String cuPassword) {
        this.cuPassword = cuPassword == null ? null : cuPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cu_phone
     *
     * @return the value of customer.cu_phone
     *
     * @mbg.generated
     */
    public String getCuPhone() {
        return cuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cu_phone
     *
     * @param cuPhone the value for customer.cu_phone
     *
     * @mbg.generated
     */
    public void setCuPhone(String cuPhone) {
        this.cuPhone = cuPhone == null ? null : cuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cu_birth
     *
     * @return the value of customer.cu_birth
     *
     * @mbg.generated
     */
    public Date getCuBirth() {
        return cuBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cu_birth
     *
     * @param cuBirth the value for customer.cu_birth
     *
     * @mbg.generated
     */
    public void setCuBirth(Date cuBirth) {
        this.cuBirth = cuBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cu_address
     *
     * @return the value of customer.cu_address
     *
     * @mbg.generated
     */
    public String getCuAddress() {
        return cuAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cu_address
     *
     * @param cuAddress the value for customer.cu_address
     *
     * @mbg.generated
     */
    public void setCuAddress(String cuAddress) {
        this.cuAddress = cuAddress == null ? null : cuAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cu_remarks
     *
     * @return the value of customer.cu_remarks
     *
     * @mbg.generated
     */
    public String getCuRemarks() {
        return cuRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cu_remarks
     *
     * @param cuRemarks the value for customer.cu_remarks
     *
     * @mbg.generated
     */
    public void setCuRemarks(String cuRemarks) {
        this.cuRemarks = cuRemarks == null ? null : cuRemarks.trim();
    }
}