package com.nf2.sss.eneity;

import java.util.Date;

public class Deliveryorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.d_startingCity
     *
     * @mbg.generated
     */
    private String dStartingcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.d_endCity
     *
     * @mbg.generated
     */
    private String dEndcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.d_hasArrived
     *
     * @mbg.generated
     */
    private String dHasarrived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.d_state
     *
     * @mbg.generated
     */
    private Integer dState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.d_riseTime
     *
     * @mbg.generated
     */
    private Date dRisetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryorder.d_remark
     *
     * @mbg.generated
     */
    private String dRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.d_startingCity
     *
     * @return the value of deliveryorder.d_startingCity
     *
     * @mbg.generated
     */
    public String getdStartingcity() {
        return dStartingcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.d_startingCity
     *
     * @param dStartingcity the value for deliveryorder.d_startingCity
     *
     * @mbg.generated
     */
    public void setdStartingcity(String dStartingcity) {
        this.dStartingcity = dStartingcity == null ? null : dStartingcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.d_endCity
     *
     * @return the value of deliveryorder.d_endCity
     *
     * @mbg.generated
     */
    public String getdEndcity() {
        return dEndcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.d_endCity
     *
     * @param dEndcity the value for deliveryorder.d_endCity
     *
     * @mbg.generated
     */
    public void setdEndcity(String dEndcity) {
        this.dEndcity = dEndcity == null ? null : dEndcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.d_hasArrived
     *
     * @return the value of deliveryorder.d_hasArrived
     *
     * @mbg.generated
     */
    public String getdHasarrived() {
        return dHasarrived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.d_hasArrived
     *
     * @param dHasarrived the value for deliveryorder.d_hasArrived
     *
     * @mbg.generated
     */
    public void setdHasarrived(String dHasarrived) {
        this.dHasarrived = dHasarrived == null ? null : dHasarrived.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.d_state
     *
     * @return the value of deliveryorder.d_state
     *
     * @mbg.generated
     */
    public Integer getdState() {
        return dState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.d_state
     *
     * @param dState the value for deliveryorder.d_state
     *
     * @mbg.generated
     */
    public void setdState(Integer dState) {
        this.dState = dState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.d_riseTime
     *
     * @return the value of deliveryorder.d_riseTime
     *
     * @mbg.generated
     */
    public Date getdRisetime() {
        return dRisetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.d_riseTime
     *
     * @param dRisetime the value for deliveryorder.d_riseTime
     *
     * @mbg.generated
     */
    public void setdRisetime(Date dRisetime) {
        this.dRisetime = dRisetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryorder.d_remark
     *
     * @return the value of deliveryorder.d_remark
     *
     * @mbg.generated
     */
    public String getdRemark() {
        return dRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryorder.d_remark
     *
     * @param dRemark the value for deliveryorder.d_remark
     *
     * @mbg.generated
     */
    public void setdRemark(String dRemark) {
        this.dRemark = dRemark == null ? null : dRemark.trim();
    }
}