package com.nf2.sss.eneity;

public class Distribution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.c_id
     *
     * @mbg.generated
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.a_id
     *
     * @mbg.generated
     */
    private String aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.d_phone
     *
     * @mbg.generated
     */
    private String dPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.d_addres
     *
     * @mbg.generated
     */
    private String dAddres;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.d_id
     *
     * @return the value of distribution.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.d_id
     *
     * @param dId the value for distribution.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.d_name
     *
     * @return the value of distribution.d_name
     *
     * @mbg.generated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.d_name
     *
     * @param dName the value for distribution.d_name
     *
     * @mbg.generated
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.c_id
     *
     * @return the value of distribution.c_id
     *
     * @mbg.generated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.c_id
     *
     * @param cId the value for distribution.c_id
     *
     * @mbg.generated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.a_id
     *
     * @return the value of distribution.a_id
     *
     * @mbg.generated
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.a_id
     *
     * @param aId the value for distribution.a_id
     *
     * @mbg.generated
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.d_phone
     *
     * @return the value of distribution.d_phone
     *
     * @mbg.generated
     */
    public String getdPhone() {
        return dPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.d_phone
     *
     * @param dPhone the value for distribution.d_phone
     *
     * @mbg.generated
     */
    public void setdPhone(String dPhone) {
        this.dPhone = dPhone == null ? null : dPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.d_addres
     *
     * @return the value of distribution.d_addres
     *
     * @mbg.generated
     */
    public String getdAddres() {
        return dAddres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.d_addres
     *
     * @param dAddres the value for distribution.d_addres
     *
     * @mbg.generated
     */
    public void setdAddres(String dAddres) {
        this.dAddres = dAddres == null ? null : dAddres.trim();
    }
}