package com.nf2.sss.eneity;

public class Distrrange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distrrange.di_id
     *
     * @mbg.generated
     */
    private Integer diId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distrrange.di_name
     *
     * @mbg.generated
     */
    private String diName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distrrange.di_price
     *
     * @mbg.generated
     */
    private Long diPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distrrange.c_id
     *
     * @mbg.generated
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distrrange.di_remarks
     *
     * @mbg.generated
     */
    private String diRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distrrange.di_id
     *
     * @return the value of distrrange.di_id
     *
     * @mbg.generated
     */
    public Integer getDiId() {
        return diId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distrrange.di_id
     *
     * @param diId the value for distrrange.di_id
     *
     * @mbg.generated
     */
    public void setDiId(Integer diId) {
        this.diId = diId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distrrange.di_name
     *
     * @return the value of distrrange.di_name
     *
     * @mbg.generated
     */
    public String getDiName() {
        return diName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distrrange.di_name
     *
     * @param diName the value for distrrange.di_name
     *
     * @mbg.generated
     */
    public void setDiName(String diName) {
        this.diName = diName == null ? null : diName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distrrange.di_price
     *
     * @return the value of distrrange.di_price
     *
     * @mbg.generated
     */
    public Long getDiPrice() {
        return diPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distrrange.di_price
     *
     * @param diPrice the value for distrrange.di_price
     *
     * @mbg.generated
     */
    public void setDiPrice(Long diPrice) {
        this.diPrice = diPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distrrange.c_id
     *
     * @return the value of distrrange.c_id
     *
     * @mbg.generated
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distrrange.c_id
     *
     * @param cId the value for distrrange.c_id
     *
     * @mbg.generated
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distrrange.di_remarks
     *
     * @return the value of distrrange.di_remarks
     *
     * @mbg.generated
     */
    public String getDiRemarks() {
        return diRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distrrange.di_remarks
     *
     * @param diRemarks the value for distrrange.di_remarks
     *
     * @mbg.generated
     */
    public void setDiRemarks(String diRemarks) {
        this.diRemarks = diRemarks == null ? null : diRemarks.trim();
    }
}