package com.nf2.sss.eneity;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_id
     *
     * @mbg.generated
     */
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_type
     *
     * @mbg.generated
     */
    private Integer oType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_handoverNo
     *
     * @mbg.generated
     */
    private String oHandoverno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_goodsName
     *
     * @mbg.generated
     */
    private String oGoodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_goodWeight
     *
     * @mbg.generated
     */
    private Integer oGoodweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_mailer
     *
     * @mbg.generated
     */
    private String oMailer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_maileraddress
     *
     * @mbg.generated
     */
    private String oMaileraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_shassress
     *
     * @mbg.generated
     */
    private String oShassress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_ordersta
     *
     * @mbg.generated
     */
    private Integer oOrdersta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_maiphone
     *
     * @mbg.generated
     */
    private String oMaiphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_consignee
     *
     * @mbg.generated
     */
    private String oConsignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_consigneephon
     *
     * @mbg.generated
     */
    private String oConsigneephon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_startingCity
     *
     * @mbg.generated
     */
    private String oStartingcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.r_midpoint
     *
     * @mbg.generated
     */
    private String rMidpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.r_endCityId
     *
     * @mbg.generated
     */
    private String rEndcityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_shippingPrice
     *
     * @mbg.generated
     */
    private Long oShippingprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_distributionPr
     *
     * @mbg.generated
     */
    private Long oDistributionpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_transporPr
     *
     * @mbg.generated
     */
    private Long oTransporpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_totalPrnvar
     *
     * @mbg.generated
     */
    private String oTotalprnvar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_vehicle
     *
     * @mbg.generated
     */
    private String oVehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_remarks
     *
     * @mbg.generated
     */
    private String oRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_id
     *
     * @return the value of orders.o_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_id
     *
     * @param oId the value for orders.o_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_type
     *
     * @return the value of orders.o_type
     *
     * @mbg.generated
     */
    public Integer getoType() {
        return oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_type
     *
     * @param oType the value for orders.o_type
     *
     * @mbg.generated
     */
    public void setoType(Integer oType) {
        this.oType = oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_handoverNo
     *
     * @return the value of orders.o_handoverNo
     *
     * @mbg.generated
     */
    public String getoHandoverno() {
        return oHandoverno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_handoverNo
     *
     * @param oHandoverno the value for orders.o_handoverNo
     *
     * @mbg.generated
     */
    public void setoHandoverno(String oHandoverno) {
        this.oHandoverno = oHandoverno == null ? null : oHandoverno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_goodsName
     *
     * @return the value of orders.o_goodsName
     *
     * @mbg.generated
     */
    public String getoGoodsname() {
        return oGoodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_goodsName
     *
     * @param oGoodsname the value for orders.o_goodsName
     *
     * @mbg.generated
     */
    public void setoGoodsname(String oGoodsname) {
        this.oGoodsname = oGoodsname == null ? null : oGoodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_goodWeight
     *
     * @return the value of orders.o_goodWeight
     *
     * @mbg.generated
     */
    public Integer getoGoodweight() {
        return oGoodweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_goodWeight
     *
     * @param oGoodweight the value for orders.o_goodWeight
     *
     * @mbg.generated
     */
    public void setoGoodweight(Integer oGoodweight) {
        this.oGoodweight = oGoodweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_mailer
     *
     * @return the value of orders.o_mailer
     *
     * @mbg.generated
     */
    public String getoMailer() {
        return oMailer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_mailer
     *
     * @param oMailer the value for orders.o_mailer
     *
     * @mbg.generated
     */
    public void setoMailer(String oMailer) {
        this.oMailer = oMailer == null ? null : oMailer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_maileraddress
     *
     * @return the value of orders.o_maileraddress
     *
     * @mbg.generated
     */
    public String getoMaileraddress() {
        return oMaileraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_maileraddress
     *
     * @param oMaileraddress the value for orders.o_maileraddress
     *
     * @mbg.generated
     */
    public void setoMaileraddress(String oMaileraddress) {
        this.oMaileraddress = oMaileraddress == null ? null : oMaileraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_shassress
     *
     * @return the value of orders.o_shassress
     *
     * @mbg.generated
     */
    public String getoShassress() {
        return oShassress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_shassress
     *
     * @param oShassress the value for orders.o_shassress
     *
     * @mbg.generated
     */
    public void setoShassress(String oShassress) {
        this.oShassress = oShassress == null ? null : oShassress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_ordersta
     *
     * @return the value of orders.o_ordersta
     *
     * @mbg.generated
     */
    public Integer getoOrdersta() {
        return oOrdersta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_ordersta
     *
     * @param oOrdersta the value for orders.o_ordersta
     *
     * @mbg.generated
     */
    public void setoOrdersta(Integer oOrdersta) {
        this.oOrdersta = oOrdersta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_maiphone
     *
     * @return the value of orders.o_maiphone
     *
     * @mbg.generated
     */
    public String getoMaiphone() {
        return oMaiphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_maiphone
     *
     * @param oMaiphone the value for orders.o_maiphone
     *
     * @mbg.generated
     */
    public void setoMaiphone(String oMaiphone) {
        this.oMaiphone = oMaiphone == null ? null : oMaiphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_consignee
     *
     * @return the value of orders.o_consignee
     *
     * @mbg.generated
     */
    public String getoConsignee() {
        return oConsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_consignee
     *
     * @param oConsignee the value for orders.o_consignee
     *
     * @mbg.generated
     */
    public void setoConsignee(String oConsignee) {
        this.oConsignee = oConsignee == null ? null : oConsignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_consigneephon
     *
     * @return the value of orders.o_consigneephon
     *
     * @mbg.generated
     */
    public String getoConsigneephon() {
        return oConsigneephon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_consigneephon
     *
     * @param oConsigneephon the value for orders.o_consigneephon
     *
     * @mbg.generated
     */
    public void setoConsigneephon(String oConsigneephon) {
        this.oConsigneephon = oConsigneephon == null ? null : oConsigneephon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_startingCity
     *
     * @return the value of orders.o_startingCity
     *
     * @mbg.generated
     */
    public String getoStartingcity() {
        return oStartingcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_startingCity
     *
     * @param oStartingcity the value for orders.o_startingCity
     *
     * @mbg.generated
     */
    public void setoStartingcity(String oStartingcity) {
        this.oStartingcity = oStartingcity == null ? null : oStartingcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.r_midpoint
     *
     * @return the value of orders.r_midpoint
     *
     * @mbg.generated
     */
    public String getrMidpoint() {
        return rMidpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.r_midpoint
     *
     * @param rMidpoint the value for orders.r_midpoint
     *
     * @mbg.generated
     */
    public void setrMidpoint(String rMidpoint) {
        this.rMidpoint = rMidpoint == null ? null : rMidpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.r_endCityId
     *
     * @return the value of orders.r_endCityId
     *
     * @mbg.generated
     */
    public String getrEndcityid() {
        return rEndcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.r_endCityId
     *
     * @param rEndcityid the value for orders.r_endCityId
     *
     * @mbg.generated
     */
    public void setrEndcityid(String rEndcityid) {
        this.rEndcityid = rEndcityid == null ? null : rEndcityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_shippingPrice
     *
     * @return the value of orders.o_shippingPrice
     *
     * @mbg.generated
     */
    public Long getoShippingprice() {
        return oShippingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_shippingPrice
     *
     * @param oShippingprice the value for orders.o_shippingPrice
     *
     * @mbg.generated
     */
    public void setoShippingprice(Long oShippingprice) {
        this.oShippingprice = oShippingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_distributionPr
     *
     * @return the value of orders.o_distributionPr
     *
     * @mbg.generated
     */
    public Long getoDistributionpr() {
        return oDistributionpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_distributionPr
     *
     * @param oDistributionpr the value for orders.o_distributionPr
     *
     * @mbg.generated
     */
    public void setoDistributionpr(Long oDistributionpr) {
        this.oDistributionpr = oDistributionpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_transporPr
     *
     * @return the value of orders.o_transporPr
     *
     * @mbg.generated
     */
    public Long getoTransporpr() {
        return oTransporpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_transporPr
     *
     * @param oTransporpr the value for orders.o_transporPr
     *
     * @mbg.generated
     */
    public void setoTransporpr(Long oTransporpr) {
        this.oTransporpr = oTransporpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_totalPrnvar
     *
     * @return the value of orders.o_totalPrnvar
     *
     * @mbg.generated
     */
    public String getoTotalprnvar() {
        return oTotalprnvar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_totalPrnvar
     *
     * @param oTotalprnvar the value for orders.o_totalPrnvar
     *
     * @mbg.generated
     */
    public void setoTotalprnvar(String oTotalprnvar) {
        this.oTotalprnvar = oTotalprnvar == null ? null : oTotalprnvar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_vehicle
     *
     * @return the value of orders.o_vehicle
     *
     * @mbg.generated
     */
    public String getoVehicle() {
        return oVehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_vehicle
     *
     * @param oVehicle the value for orders.o_vehicle
     *
     * @mbg.generated
     */
    public void setoVehicle(String oVehicle) {
        this.oVehicle = oVehicle == null ? null : oVehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_remarks
     *
     * @return the value of orders.o_remarks
     *
     * @mbg.generated
     */
    public String getoRemarks() {
        return oRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_remarks
     *
     * @param oRemarks the value for orders.o_remarks
     *
     * @mbg.generated
     */
    public void setoRemarks(String oRemarks) {
        this.oRemarks = oRemarks == null ? null : oRemarks.trim();
    }
}