package com.nf2.sss.eneity;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r_id
     *
     * @mbg.generated
     */
    private String rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r_name
     *
     * @mbg.generated
     */
    private String rName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.p_id
     *
     * @mbg.generated
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.o_startingCity
     *
     * @mbg.generated
     */
    private String oStartingcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.p_midpoint
     *
     * @mbg.generated
     */
    private String pMidpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r_midpoint
     *
     * @mbg.generated
     */
    private String rMidpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.p_endCity
     *
     * @mbg.generated
     */
    private String pEndcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r_endCityId
     *
     * @mbg.generated
     */
    private String rEndcityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r_transporPr
     *
     * @mbg.generated
     */
    private Long rTransporpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.r_remarks
     *
     * @mbg.generated
     */
    private String rRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r_id
     *
     * @return the value of route.r_id
     *
     * @mbg.generated
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r_id
     *
     * @param rId the value for route.r_id
     *
     * @mbg.generated
     */
    public void setrId(String rId) {
        this.rId = rId == null ? null : rId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r_name
     *
     * @return the value of route.r_name
     *
     * @mbg.generated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r_name
     *
     * @param rName the value for route.r_name
     *
     * @mbg.generated
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.p_id
     *
     * @return the value of route.p_id
     *
     * @mbg.generated
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.p_id
     *
     * @param pId the value for route.p_id
     *
     * @mbg.generated
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.o_startingCity
     *
     * @return the value of route.o_startingCity
     *
     * @mbg.generated
     */
    public String getoStartingcity() {
        return oStartingcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.o_startingCity
     *
     * @param oStartingcity the value for route.o_startingCity
     *
     * @mbg.generated
     */
    public void setoStartingcity(String oStartingcity) {
        this.oStartingcity = oStartingcity == null ? null : oStartingcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.p_midpoint
     *
     * @return the value of route.p_midpoint
     *
     * @mbg.generated
     */
    public String getpMidpoint() {
        return pMidpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.p_midpoint
     *
     * @param pMidpoint the value for route.p_midpoint
     *
     * @mbg.generated
     */
    public void setpMidpoint(String pMidpoint) {
        this.pMidpoint = pMidpoint == null ? null : pMidpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r_midpoint
     *
     * @return the value of route.r_midpoint
     *
     * @mbg.generated
     */
    public String getrMidpoint() {
        return rMidpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r_midpoint
     *
     * @param rMidpoint the value for route.r_midpoint
     *
     * @mbg.generated
     */
    public void setrMidpoint(String rMidpoint) {
        this.rMidpoint = rMidpoint == null ? null : rMidpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.p_endCity
     *
     * @return the value of route.p_endCity
     *
     * @mbg.generated
     */
    public String getpEndcity() {
        return pEndcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.p_endCity
     *
     * @param pEndcity the value for route.p_endCity
     *
     * @mbg.generated
     */
    public void setpEndcity(String pEndcity) {
        this.pEndcity = pEndcity == null ? null : pEndcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r_endCityId
     *
     * @return the value of route.r_endCityId
     *
     * @mbg.generated
     */
    public String getrEndcityid() {
        return rEndcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r_endCityId
     *
     * @param rEndcityid the value for route.r_endCityId
     *
     * @mbg.generated
     */
    public void setrEndcityid(String rEndcityid) {
        this.rEndcityid = rEndcityid == null ? null : rEndcityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r_transporPr
     *
     * @return the value of route.r_transporPr
     *
     * @mbg.generated
     */
    public Long getrTransporpr() {
        return rTransporpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r_transporPr
     *
     * @param rTransporpr the value for route.r_transporPr
     *
     * @mbg.generated
     */
    public void setrTransporpr(Long rTransporpr) {
        this.rTransporpr = rTransporpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.r_remarks
     *
     * @return the value of route.r_remarks
     *
     * @mbg.generated
     */
    public String getrRemarks() {
        return rRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.r_remarks
     *
     * @param rRemarks the value for route.r_remarks
     *
     * @mbg.generated
     */
    public void setrRemarks(String rRemarks) {
        this.rRemarks = rRemarks == null ? null : rRemarks.trim();
    }
}