package com.nf2.sss.eneity;

public class Usertb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertb.u_id
     *
     * @mbg.generated
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertb.u_name
     *
     * @mbg.generated
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertb.u_remarks
     *
     * @mbg.generated
     */
    private String uRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertb.u_id
     *
     * @return the value of usertb.u_id
     *
     * @mbg.generated
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertb.u_id
     *
     * @param uId the value for usertb.u_id
     *
     * @mbg.generated
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertb.u_name
     *
     * @return the value of usertb.u_name
     *
     * @mbg.generated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertb.u_name
     *
     * @param uName the value for usertb.u_name
     *
     * @mbg.generated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertb.u_remarks
     *
     * @return the value of usertb.u_remarks
     *
     * @mbg.generated
     */
    public String getuRemarks() {
        return uRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertb.u_remarks
     *
     * @param uRemarks the value for usertb.u_remarks
     *
     * @mbg.generated
     */
    public void setuRemarks(String uRemarks) {
        this.uRemarks = uRemarks == null ? null : uRemarks.trim();
    }
}