package com.nf2.sss.eneity;

import java.util.Date;

public class Vehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_id
     *
     * @mbg.generated
     */
    private String vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_carModel
     *
     * @mbg.generated
     */
    private String vCarmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_placeof
     *
     * @mbg.generated
     */
    private String vPlaceof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_routEnumb
     *
     * @mbg.generated
     */
    private String vRoutenumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_dateOfProd
     *
     * @mbg.generated
     */
    private Date vDateofprod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_dateOfPurch
     *
     * @mbg.generated
     */
    private Date vDateofpurch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_remarks
     *
     * @mbg.generated
     */
    private String vRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_id
     *
     * @return the value of vehicle.v_id
     *
     * @mbg.generated
     */
    public String getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_id
     *
     * @param vId the value for vehicle.v_id
     *
     * @mbg.generated
     */
    public void setvId(String vId) {
        this.vId = vId == null ? null : vId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_carModel
     *
     * @return the value of vehicle.v_carModel
     *
     * @mbg.generated
     */
    public String getvCarmodel() {
        return vCarmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_carModel
     *
     * @param vCarmodel the value for vehicle.v_carModel
     *
     * @mbg.generated
     */
    public void setvCarmodel(String vCarmodel) {
        this.vCarmodel = vCarmodel == null ? null : vCarmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_placeof
     *
     * @return the value of vehicle.v_placeof
     *
     * @mbg.generated
     */
    public String getvPlaceof() {
        return vPlaceof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_placeof
     *
     * @param vPlaceof the value for vehicle.v_placeof
     *
     * @mbg.generated
     */
    public void setvPlaceof(String vPlaceof) {
        this.vPlaceof = vPlaceof == null ? null : vPlaceof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_routEnumb
     *
     * @return the value of vehicle.v_routEnumb
     *
     * @mbg.generated
     */
    public String getvRoutenumb() {
        return vRoutenumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_routEnumb
     *
     * @param vRoutenumb the value for vehicle.v_routEnumb
     *
     * @mbg.generated
     */
    public void setvRoutenumb(String vRoutenumb) {
        this.vRoutenumb = vRoutenumb == null ? null : vRoutenumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_dateOfProd
     *
     * @return the value of vehicle.v_dateOfProd
     *
     * @mbg.generated
     */
    public Date getvDateofprod() {
        return vDateofprod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_dateOfProd
     *
     * @param vDateofprod the value for vehicle.v_dateOfProd
     *
     * @mbg.generated
     */
    public void setvDateofprod(Date vDateofprod) {
        this.vDateofprod = vDateofprod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_dateOfPurch
     *
     * @return the value of vehicle.v_dateOfPurch
     *
     * @mbg.generated
     */
    public Date getvDateofpurch() {
        return vDateofpurch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_dateOfPurch
     *
     * @param vDateofpurch the value for vehicle.v_dateOfPurch
     *
     * @mbg.generated
     */
    public void setvDateofpurch(Date vDateofpurch) {
        this.vDateofpurch = vDateofpurch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_remarks
     *
     * @return the value of vehicle.v_remarks
     *
     * @mbg.generated
     */
    public String getvRemarks() {
        return vRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_remarks
     *
     * @param vRemarks the value for vehicle.v_remarks
     *
     * @mbg.generated
     */
    public void setvRemarks(String vRemarks) {
        this.vRemarks = vRemarks == null ? null : vRemarks.trim();
    }
}